/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria.vistas;

import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import veterinaria.controlador.ClienteData;
import veterinaria.controlador.Conexion;
import veterinaria.controlador.MascotaData;
import veterinaria.controlador.TratamientoData;
import veterinaria.controlador.VisitaData;
import veterinaria.modelo.Cliente;
import veterinaria.modelo.Mascota;
import veterinaria.modelo.Tratamiento;
import veterinaria.modelo.Visita;

/**
 *
 * @author Usuario
 */
public class FormularioVisita extends javax.swing.JInternalFrame {

    /**
     * Creates new form Agregar
     */
    Conexion conexion;
    ClienteData clienteData;
    MascotaData mascotaData;
    TratamientoData tratamientoData;
    VisitaData visitaData;
    List<Mascota> mascotas;
    List<Visita> visitas = null;

    public FormularioVisita() {

        initComponents();
        jrbBaja.setEnabled(false);
        jrbAlta.setEnabled(false);
        btnNuevaMasc.setEnabled(false);
        try {
            conexion = new Conexion();
            clienteData = new ClienteData(conexion);
            tratamientoData = new TratamientoData(conexion);
            mascotaData = new MascotaData(conexion);
            visitaData = new VisitaData(conexion);
            agregarTratamientos();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormularioVisita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
     public FormularioVisita(int dni) {

        initComponents();
        jrbBaja.setEnabled(false);
        jrbAlta.setEnabled(false);
        btnNuevaMasc.setEnabled(false);
        jtDni.setText(dni+"");
        
        try {
            conexion = new Conexion();
            clienteData = new ClienteData(conexion);
            tratamientoData = new TratamientoData(conexion);
            mascotaData = new MascotaData(conexion);
            visitaData = new VisitaData(conexion);
            agregarTratamientos();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormularioVisita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jtDni = new javax.swing.JTextField();
        jtDetalle = new javax.swing.JTextField();
        jcbActivo = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbMascota = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jrbAlta = new javax.swing.JRadioButton();
        jrbBaja = new javax.swing.JRadioButton();
        jDate = new com.toedter.calendar.JDateChooser();
        jtPeso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtMedicamento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtImporte = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jcbTratamiento = new javax.swing.JComboBox<>();
        btnTratamiento = new javax.swing.JButton();
        btnNuevaMasc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(218, 229, 208));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 62, 62), 2, true));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jtDni.setBackground(new java.awt.Color(213, 55, 132));
        jtDni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtDni.setForeground(new java.awt.Color(255, 255, 255));
        jtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDniKeyTyped(evt);
            }
        });

        jtDetalle.setBackground(new java.awt.Color(247, 188, 32));
        jtDetalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtDetalle.setForeground(new java.awt.Color(255, 255, 255));

        jcbActivo.setBackground(new java.awt.Color(255, 255, 255));
        jcbActivo.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jcbActivo.setText("ACTIVO (seleccione en caso de continuar con el tratamiento)");

        btnGuardar.setBackground(new java.awt.Color(36, 130, 186));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(36, 130, 186));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel1.setText("PESO ACTUAL");

        jLabel2.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel2.setText("FECHA DE VISITA");

        jLabel6.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel6.setText("MASCOTA");

        jLabel7.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel7.setText("DNI CLIENTE");

        jLabel11.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel11.setText("DETALLE DE VISITA (síntomas o afección)");

        jcbMascota.setBackground(new java.awt.Color(213, 55, 132));
        jcbMascota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMascotaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel4.setText("TRATAMIENTOS  ACTIVOS");

        jTable.setBackground(new java.awt.Color(36, 130, 186));
        jTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTable.setForeground(new java.awt.Color(255, 255, 255));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FECHA", "TIPO DE TRATAMIENTO", "DESCRIPCION", "MEDICAMENTO", "IMPORTE"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        btnBuscar.setBackground(new java.awt.Color(213, 55, 132));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR CLIENTE");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jrbAlta.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbAlta);
        jrbAlta.setFont(new java.awt.Font("Lato", 1, 11)); // NOI18N
        jrbAlta.setText("CONTINUAR  CON  EL  TRATAMIENTO");
        jrbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAltaActionPerformed(evt);
            }
        });

        jrbBaja.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbBaja);
        jrbBaja.setFont(new java.awt.Font("Lato", 1, 11)); // NOI18N
        jrbBaja.setText("FINALIZAR  EL  TRATAMIENTO");
        jrbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBajaActionPerformed(evt);
            }
        });

        jDate.setBackground(new java.awt.Color(247, 188, 32));

        jtPeso.setBackground(new java.awt.Color(247, 188, 32));
        jtPeso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtPeso.setForeground(new java.awt.Color(255, 255, 255));
        jtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPesoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel5.setText("MEDICAMENTO");

        jtDescripcion.setBackground(new java.awt.Color(247, 188, 32));
        jtDescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtDescripcion.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel12.setText("SELECCIONE  EL  TIPO  DE  TRATAMIENTO   O  AGREGUE UNO NUEVO");

        jtMedicamento.setBackground(new java.awt.Color(247, 188, 32));
        jtMedicamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtMedicamento.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel13.setText("DESCRIPCION");

        jLabel14.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel14.setText("IMPORTE");

        jtImporte.setBackground(new java.awt.Color(247, 188, 32));
        jtImporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtImporte.setForeground(new java.awt.Color(255, 255, 255));
        jtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtImporteKeyTyped(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jcbTratamiento.setBackground(new java.awt.Color(247, 188, 32));
        jcbTratamiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnTratamiento.setBackground(new java.awt.Color(36, 130, 186));
        btnTratamiento.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        btnTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        btnTratamiento.setText("Agregar nuevo");
        btnTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratamientoActionPerformed(evt);
            }
        });

        btnNuevaMasc.setBackground(new java.awt.Color(213, 55, 132));
        btnNuevaMasc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevaMasc.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaMasc.setText("NUEVA MASCOTA");
        btnNuevaMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaMascActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jcbMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(btnNuevaMasc))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jrbAlta)
                                .addGap(18, 18, 18)
                                .addComponent(jrbBaja))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(jtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbActivo)
                                            .addComponent(jtDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(61, 61, 61)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jcbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTratamiento))
                                    .addComponent(jLabel13)
                                    .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(jcbMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnNuevaMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbBaja)
                    .addComponent(jrbAlta))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTratamiento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbActivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.setForeground(new java.awt.Color(55, 62, 62));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/vistas/imagenes/logo2.jpg"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(247, 188, 32));
        jLabel15.setText("N");

        jLabel16.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(36, 130, 186));
        jLabel16.setText("I");

        jLabel17.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(213, 55, 132));
        jLabel17.setText("S");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(247, 188, 32));
        jLabel19.setText("I");

        jLabel18.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(36, 130, 186));
        jLabel18.setText("T");

        jLabel20.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(213, 55, 132));
        jLabel20.setText("A");

        jLabel21.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(247, 188, 32));
        jLabel21.setText("D");

        jLabel22.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(36, 130, 186));
        jLabel22.setText("E");

        jLabel23.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(213, 55, 132));
        jLabel23.setText("A");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(247, 188, 32));
        jLabel24.setText("T");

        jLabel25.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(36, 130, 186));
        jLabel25.setText("I");

        jLabel26.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(213, 55, 132));
        jLabel26.setText("N");

        jLabel28.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(36, 130, 186));
        jLabel28.setText("E");

        jLabel27.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(247, 188, 32));
        jLabel27.setText(" V");

        jLabel29.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(213, 55, 132));
        jLabel29.setText("Ó");

        jLabel30.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(247, 188, 32));
        jLabel30.setText("C");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(2, 2, 2)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(13, 13, 13))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Cliente cliente = null;
        jcbMascota.removeAllItems();

        try {
            int dni = Integer.parseInt(jtDni.getText());
            cliente = clienteData.buscarClienteDni(dni);
            if (!(cliente == null)) {
                mascotas = mascotaData.obtenerMascotasPorDuenio(cliente.getIdCliente());
                if(mascotas.isEmpty()){
                    JOptionPane.showMessageDialog(this, "El cliente no tiene ninguna mascota registrada. Debe registrar una mascota para realizar una visita");
                }
                agregarMascotas();
                jrbBaja.setEnabled(true);
                jrbAlta.setEnabled(true);
                btnNuevaMasc.setEnabled(true);
            } else {
                jcbMascota.removeAllItems();
                //cancelar=2 , no =1 , si=0
                int confirmar = JOptionPane.showConfirmDialog(this, "Error, el dni insegresado. no corresponde a ningún cliente registrado. ¿Desea registrarse?");
                if (confirmar == 0) {

                    FormularioCliente fc = new FormularioCliente(dni);
                    Principal.fondo.add(fc);
                    fc.toFront();
                    fc.setVisible(true);
                    this.dispose();
                }
            }
        } catch (Exception e) {
            System.out.println("Error en buscar");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jcbMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMascotaActionPerformed

        try {
            cargarTabla();
        } catch (Exception e) {

        }
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jcbMascotaActionPerformed

    private void jrbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBajaActionPerformed
        if (jrbBaja.isSelected()) {

            try {
                //guardo la posicion que esta seleccionada en la fila
                int posicionFila = jTable.getSelectedRow();
                //obtengo el id,nombre de la materia seleccionada 
                String tipoT = (String) jTable.getValueAt(posicionFila, 1);
                Mascota m = (Mascota) jcbMascota.getSelectedItem();
                visitas = visitaData.obtenerVisitasxMascotaEActivo(m.getIdMascota());
                Tratamiento t = visitas.get(posicionFila).getTratamiento();
                //cancelar=2 , no =1 , si=0
                int confirmar = JOptionPane.showConfirmDialog(this, "¿Está seguro de finalizar con el tratamiento?");
                if (confirmar == 0) {
                    tratamientoData.bajaTratamiento(t.getIdTratamiento());
                    cargarTabla();
                    buttonGroup1.clearSelection();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar la fila del tratamiento que desea finalizar");
            }
            jcbTratamiento.setEnabled(true);
            btnTratamiento.setEnabled(true);
        }
    }//GEN-LAST:event_jrbBajaActionPerformed

    private void jrbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAltaActionPerformed
        if (jrbAlta.isSelected()) {
            try {
                //guardo la posicion que esta seleccionada en la fila
                int posicionFila = jTable.getSelectedRow();
                Tratamiento ts = visitas.get(posicionFila).getTratamiento();
//                jtTipo.setText(ts.getTipoTratamiento());
                jtDescripcion.setText(ts.getDescripcion());
                jtMedicamento.setText(ts.getMedicamento());
                jtImporte.setText(ts.getImporte() + "");

                jcbTratamiento.setEnabled(false);
                btnTratamiento.setEnabled(false);
            } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, "Debe seleccionar la fila del tratamiento con el que desea continuar");
            }
        }
    }//GEN-LAST:event_jrbAltaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamientoActionPerformed
        String respuesta = JOptionPane.showInputDialog("Ingrese un tratamiento");
        jcbTratamiento.addItem(respuesta);
    }//GEN-LAST:event_btnTratamientoActionPerformed

    private void jtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && c != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_jtPesoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (jDate.getDate() == null || jtPeso.getText().isEmpty() || jtDescripcion.getText().isEmpty() || jtMedicamento.getText().isEmpty() || jtImporte.getText().isEmpty() || jcbMascota.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Para registrar la visita de la mascota es necesario que complete todos los campos");
        } else {
            Mascota m = (Mascota) jcbMascota.getSelectedItem();
            Date f = jDate.getDate();
            LocalDate fecha = f.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            double peso = Double.parseDouble(jtPeso.getText());
            String detalle = jtDetalle.getText();
            Boolean activo = jcbActivo.isSelected();
            String descripcion = jtDescripcion.getText();
            String tipoT = "";
            if (jrbAlta.isSelected()) {
                try {
                    int posicionFila = jTable.getSelectedRow();
                    Tratamiento ts = visitas.get(posicionFila).getTratamiento();
                    tipoT = ts.getTipoTratamiento();
                } catch (Exception e) {

                }

            } else {
                tipoT = (String) jcbTratamiento.getSelectedItem();
            }
            String medicamento = jtMedicamento.getText();
            double importe = Double.parseDouble(jtImporte.getText());
            Tratamiento t = new Tratamiento(descripcion, medicamento, importe, tipoT, activo);
            t = tratamientoData.guardarTratamiento(t);
            Visita v = new Visita(m, fecha, detalle, peso, t, true);
            boolean aux = visitaData.guardarVisita(v);
            if (aux) {
                JOptionPane.showMessageDialog(this, "Se registró correctamente la visita ");
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar registrar la visita. Verifique los datos ");
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDniKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jtDniKeyTyped

    private void btnNuevaMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaMascActionPerformed
        FormularioMascota fm = new FormularioMascota();
        Principal.fondo.add(fm);
        fm.toFront();
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNuevaMascActionPerformed

    private void jtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtImporteKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && c != '.') {
            evt.consume();
        }

    }//GEN-LAST:event_jtImporteKeyTyped

    public void agregarMascotas() {
        if (mascotas != null) {
            for (Mascota it : mascotas) {
                jcbMascota.addItem(it);
            }
        }

    }

    public void agregarTratamientos() {
        {
            jcbTratamiento.addItem("vacunación");
            jcbTratamiento.addItem("enfermedad");
            jcbTratamiento.addItem("curaciones");
            jcbTratamiento.addItem("baño y corte de pelo");
            jcbTratamiento.addItem("castración");
            jcbTratamiento.addItem("desparasitación");
        }
    }

    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
        modelo.setRowCount(0);
        Mascota m = (Mascota) jcbMascota.getSelectedItem();
        visitas = visitaData.obtenerVisitasxMascotaEActivo(m.getIdMascota());
        if (visitas != null) {
            jrbBaja.setEnabled(true);
            jrbAlta.setEnabled(true);
            for (Visita it : visitas) {
                modelo.addRow(new Object[]{it.getFechaVisita(), it.getTratamiento().getTipoTratamiento(), it.getTratamiento().getDescripcion(), it.getTratamiento().getMedicamento(), it.getTratamiento().getImporte()});
            }
            jTable.setModel(modelo);
        }
    }

    public void limpiar() {
//           jtTipo.setText("");
        jtDescripcion.setText("");
        jtMedicamento.setText("");
        jtImporte.setText("");

        jtPeso.setText("");
        jtDetalle.setText("");
        jcbActivo.setSelected(false);
        jtDni.setText("");
        jDate.setDate(null);
        jcbMascota.removeAllItems();
        jTable.removeAll();
        buttonGroup1.clearSelection();
        jrbAlta.setEnabled(false);
        jrbBaja.setEnabled(false);

        jcbTratamiento.setEnabled(true);
        btnTratamiento.setEnabled(true);
        btnNuevaMasc.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevaMasc;
    private javax.swing.JButton btnTratamiento;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable;
    private javax.swing.JCheckBox jcbActivo;
    private javax.swing.JComboBox<Mascota> jcbMascota;
    private javax.swing.JComboBox<String> jcbTratamiento;
    private javax.swing.JRadioButton jrbAlta;
    private javax.swing.JRadioButton jrbBaja;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtDetalle;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtImporte;
    private javax.swing.JTextField jtMedicamento;
    private javax.swing.JTextField jtPeso;
    // End of variables declaration//GEN-END:variables
}
