/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria.vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import veterinaria.controlador.ClienteData;
import veterinaria.controlador.Conexion;
import veterinaria.controlador.MascotaData;
import veterinaria.controlador.VisitaData;
import veterinaria.modelo.Cliente;
import veterinaria.modelo.Mascota;
import veterinaria.modelo.Visita;

/**
 *
 * @author Usuario
 */
public class FormularioConsultaTratamiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form Agregar
     */
    Conexion conexion;
    MascotaData mascotaData;
    VisitaData visitaData;
    List<Mascota> mascotas = new ArrayList<>();
    List<Visita> visitas;

    public FormularioConsultaTratamiento() {

        initComponents();
        try {
            conexion = new Conexion();
//            clienteData = new ClienteData(conexion);
            mascotaData = new MascotaData(conexion);
            visitaData = new VisitaData(conexion);
//            clientes = clienteData.obtenerClientes();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormularioConsultaTratamiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jtTipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarTratamiento = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        fInicio = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fFin = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVisita = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtTipo.setBackground(new java.awt.Color(213, 55, 132));
        jtTipo.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel8.setText("BUSCAR  POR  TIPO  DE  TRATAMIENTO");

        btnBuscarTratamiento.setBackground(new java.awt.Color(247, 188, 32));
        btnBuscarTratamiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarTratamiento.setText("BUSCAR");
        btnBuscarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTratamientoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel11.setText("BUSCAR  POR  FECHA");

        fInicio.setBackground(new java.awt.Color(213, 55, 132));

        jLabel12.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel12.setText("DESDE");

        jLabel13.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel13.setText("HASTA");

        fFin.setBackground(new java.awt.Color(213, 55, 132));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtTipo)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscarTratamiento))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(fInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fFin, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(101, 101, 101)))
                    .addComponent(jLabel11))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscarTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/vistas/imagenes/logo2.jpg"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(36, 130, 186));
        jLabel16.setText("O");

        jLabel17.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(213, 55, 132));
        jLabel17.setText("N");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(247, 188, 32));
        jLabel19.setText("S");

        jLabel18.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(36, 130, 186));
        jLabel18.setText("U");

        jLabel20.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(213, 55, 132));
        jLabel20.setText("L");

        jLabel21.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(247, 188, 32));
        jLabel21.setText("T");

        jLabel22.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(36, 130, 186));
        jLabel22.setText("A");

        jLabel23.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(213, 55, 132));
        jLabel23.setText("T");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(247, 188, 32));
        jLabel24.setText("E");

        jLabel25.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(36, 130, 186));
        jLabel25.setText("N");

        jLabel26.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(213, 55, 132));
        jLabel26.setText("T");

        jLabel28.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(36, 130, 186));
        jLabel28.setText("A");

        jLabel27.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(247, 188, 32));
        jLabel27.setText("C");

        jLabel29.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(213, 55, 132));
        jLabel29.setText("I");

        jLabel30.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(247, 188, 32));
        jLabel30.setText("A");

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(247, 188, 32));
        jLabel31.setText("R");

        jLabel32.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(36, 130, 186));
        jLabel32.setText("M");

        jLabel33.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(213, 55, 132));
        jLabel33.setText("T");

        jLabel34.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(247, 188, 32));
        jLabel34.setText("O");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(2, 2, 2)
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addComponent(jLabel34)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(7, 7, 7))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTableVisita.setBackground(new java.awt.Color(36, 130, 186));
        jTableVisita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableVisita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Alias", "Fecha", "Detalle", "Peso", "Tipo tratamiento", "Descripcion", "Medicamento", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jTableVisita);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel14.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel14.setText("VISITAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(337, 337, 337))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTratamientoActionPerformed
        visitas = null;
        if ((jtTipo.getText().isEmpty() && fInicio.getDate() == null)) {
            JOptionPane.showMessageDialog(this, "Error. Para realizar la busqueda se necesita que complete al menos uno de los filtros");
        } else {
            if ((fInicio.getDate() == null && fFin.getDate() != null) || (fInicio.getDate() != null && fFin.getDate() == null)) {
                JOptionPane.showMessageDialog(this, "Error. Para realizar la busqueda por fecha es necesario que tanto que las dos fechas se encuentren completas");
            } else {
                try {
                    String tipo = "";
                    String fechaInicio = "";
                    String fechaFin = "";

                    if (jtTipo.getText().isEmpty()) {
                        Date f = fInicio.getDate();
                        Date f2 = fFin.getDate();
                        if (f.after(f2)) {
                            JOptionPane.showMessageDialog(this, "Error, la fecha de inicio que indicó es posterior a la fecha de finalización. Ingrese correctamente las fechas");
                        } else {
                            fechaInicio = (f.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()).toString();
                            fechaFin = (f2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()).toString();
                            visitas = visitaData.obtenerVisitasxFecha(fechaInicio, fechaFin);
                            if (visitas.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "no se encuentra ninguna visita registrada con la fecha ingresada.");
                            } else {
                                cargarTabla();
                            }
                        }
                    } else {
                        if (!jtTipo.getText().isEmpty() && fInicio.getDate() == null) {
                            tipo = jtTipo.getText();
                            visitas = visitaData.obtenerVisitasxTratamiento(tipo);
                            if (visitas.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "no se encuentra ninguna visita registrada con el tratamiento ingresado. Verifique el nombre del tratamiento");
                            } else {
                                cargarTabla();
                            }

                        } else {
                            tipo = jtTipo.getText();
                            Date f = fInicio.getDate();
                            Date f2 = fFin.getDate();
                            fechaInicio = (f.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()).toString();
                            fechaFin = (f2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()).toString();
                            visitas = visitaData.obtenerVisitasxTyF(tipo, fechaInicio, fechaFin);

                            if (visitas.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "no se encuentra ninguna visita registrada con el tratamiento y fecha ingresados.");
                            } else {
                                cargarTabla();
                            }
                        }
                    }

                } catch (Exception e) {
                    System.out.println("Error dentro de buscar tratamiento");
                }
            }
        }

    }//GEN-LAST:event_btnBuscarTratamientoActionPerformed

    private void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTableVisita.getModel();
        modelo.setRowCount(0);
        for (Visita it : visitas) {
            LocalDate fecha = it.getFechaVisita();
            String detalle = it.getDetalle();
            double peso = it.getPeso();
            String tipoT = it.getTratamiento().getTipoTratamiento();
            String descripcion = it.getTratamiento().getDescripcion();
            String medicamento = it.getTratamiento().getMedicamento();
            double importe = it.getTratamiento().getImporte();
            modelo.addRow(new Object[]{it.getMascota().getAlias(), fecha, detalle, peso, tipoT, descripcion, medicamento, importe});
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTratamiento;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser fFin;
    private com.toedter.calendar.JDateChooser fInicio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableVisita;
    private javax.swing.JTextField jtTipo;
    // End of variables declaration//GEN-END:variables
}
