/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria.vistas;

import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import veterinaria.controlador.ClienteData;
import veterinaria.controlador.Conexion;
import veterinaria.controlador.MascotaData;
import veterinaria.controlador.TratamientoData;
import veterinaria.controlador.VisitaData;
import veterinaria.modelo.Cliente;
import veterinaria.modelo.Mascota;
import veterinaria.modelo.Tratamiento;
import veterinaria.modelo.Visita;

/**
 *
 * @author Usuario
 */
public class FormularioAlta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Agregar
     */
    Conexion conexion;
    ClienteData clienteData;
    MascotaData mascotaData;
    TratamientoData tratamientoData;
    VisitaData visitaData;
    List<Mascota> mascotas;
    List<Visita> visitas = null;
    List<Cliente> clientes;
    List<Visita> tratamientosInactivos;

    public FormularioAlta() {

        initComponents();
        try {
            conexion = new Conexion();
            clienteData = new ClienteData(conexion);
            tratamientoData = new TratamientoData(conexion);
            mascotaData = new MascotaData(conexion);
            visitaData = new VisitaData(conexion);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormularioAlta.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarClientes();
        agregarMascotas();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbMascota = new javax.swing.JComboBox<>();
        btnAltaC = new javax.swing.JButton();
        jcbCliente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnAltaM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnAltaT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 62, 62), 2, true));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel6.setText("MASCOTAS INACTIVAS");

        jLabel7.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel7.setText("CLIENTES INACTIVOS");

        jcbMascota.setBackground(new java.awt.Color(213, 55, 132));
        jcbMascota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnAltaC.setBackground(new java.awt.Color(213, 55, 132));
        btnAltaC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAltaC.setForeground(new java.awt.Color(255, 255, 255));
        btnAltaC.setText("DAR ALTA");
        btnAltaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaCActionPerformed(evt);
            }
        });

        jcbCliente.setBackground(new java.awt.Color(213, 55, 132));

        jLabel8.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel8.setText("TRATAMIENTOS INACTIVOS");

        btnAltaM.setBackground(new java.awt.Color(213, 55, 132));
        btnAltaM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAltaM.setForeground(new java.awt.Color(255, 255, 255));
        btnAltaM.setText("DAR ALTA");
        btnAltaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaMActionPerformed(evt);
            }
        });

        jTable.setBackground(new java.awt.Color(247, 188, 32));
        jTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "codigo", "Alias", "Tipo tratamiento", "Descripcion", "Medicamento", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        btnAltaT.setBackground(new java.awt.Color(213, 55, 132));
        btnAltaT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAltaT.setForeground(new java.awt.Color(255, 255, 255));
        btnAltaT.setText("DAR DE ALTA TRATAMIENTO");
        btnAltaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6)
                                        .addComponent(jcbMascota, 0, 322, Short.MAX_VALUE)
                                        .addComponent(jcbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAltaC)
                                        .addComponent(btnAltaM)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSeparator1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAltaT)))
                        .addGap(0, 291, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAltaM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAltaC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAltaT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.setForeground(new java.awt.Color(55, 62, 62));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/vistas/imagenes/logo2.jpg"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(36, 130, 186));
        jLabel16.setText("E");

        jLabel17.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(213, 55, 132));
        jLabel17.setText("S");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(247, 188, 32));
        jLabel19.setText("T");

        jLabel18.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(36, 130, 186));
        jLabel18.setText("I");

        jLabel20.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(213, 55, 132));
        jLabel20.setText("O");

        jLabel21.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(247, 188, 32));
        jLabel21.setText("N");

        jLabel22.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(36, 130, 186));
        jLabel22.setText("A");

        jLabel23.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(213, 55, 132));
        jLabel23.setText("R");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(247, 188, 32));
        jLabel24.setText("A");

        jLabel25.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(36, 130, 186));
        jLabel25.setText("S");

        jLabel26.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(213, 55, 132));
        jLabel26.setText("T");

        jLabel28.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(36, 130, 186));
        jLabel28.setText("L");

        jLabel27.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(247, 188, 32));
        jLabel27.setText("G");

        jLabel30.setFont(new java.awt.Font("AngsanaUPC", 0, 45)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(247, 188, 32));
        jLabel30.setText("A");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(26, 26, 26)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(70, 70, 70))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel30)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(13, 13, 13))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaCActionPerformed
        try {
            Cliente c = (Cliente) jcbCliente.getSelectedItem();
            boolean b = clienteData.activarCliente(c.getIdCliente());
            if (b) {
                JOptionPane.showMessageDialog(this, "Se dio de alta al cliente " + c + " correctamente");
                jcbCliente.removeAllItems();
                agregarClientes();
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar dar de alta al cliente");
            }
        } catch (Exception e) {
            System.out.println("Debe seleccionar el cliente primero");
        }
    }//GEN-LAST:event_btnAltaCActionPerformed

    private void btnAltaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaMActionPerformed
        try {
            Mascota m = (Mascota) jcbMascota.getSelectedItem();
            boolean b = mascotaData.activarMascota(m.getIdMascota());
            if (b) {
                JOptionPane.showMessageDialog(this, "Se dio de alta a la mascota " + m + " correctamente");
                jcbMascota.removeAllItems();
                agregarMascotas();
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar dar de alta la mascota");
            }
        } catch (Exception e) {
            System.out.println("Debe seleccionar la mascota primero");
        }

    }//GEN-LAST:event_btnAltaMActionPerformed

    private void btnAltaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaTActionPerformed

        try {
            //guardo la posicion que esta seleccionada en la fila
            int posicionFila = jTable.getSelectedRow();
            int idTratamiento = (int) jTable.getValueAt(posicionFila, 0);
            boolean aux = tratamientoData.activarTratamiento(idTratamiento);
            if (aux) {
                JOptionPane.showMessageDialog(this, "Se dio de alta el tratamiento");
                jTable.removeAll();

                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al intentar dar de alta el tratamiento");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar la fila del tratamiento con el que desea continuar");
        }
    }//GEN-LAST:event_btnAltaTActionPerformed

    private void agregarMascotas() {
        mascotas = mascotaData.obtenerMascotasInativas();
        if (mascotas != null) {
            for (Mascota it : mascotas) {
                jcbMascota.addItem(it);
            }
        }

    }

    private void agregarClientes() {
        clientes = clienteData.obtenerClientesInactivos();
        for (Cliente it : clientes) {
            jcbCliente.addItem(it);
        }
    }

    private void cargarTabla() {
        tratamientosInactivos = visitaData.visitasTratamientoInactivo();
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
        modelo.setRowCount(0);
        for (Visita it : tratamientosInactivos) {
            String alias = it.getMascota().getAlias();
            String tipoT = it.getTratamiento().getTipoTratamiento();
            String descripcion = it.getTratamiento().getDescripcion();
            String medicamento = it.getTratamiento().getMedicamento();
            double importe = it.getTratamiento().getImporte();
            modelo.addRow(new Object[]{it.getTratamiento().getIdTratamiento(), alias, tipoT, descripcion, medicamento, importe});
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaC;
    private javax.swing.JButton btnAltaM;
    private javax.swing.JButton btnAltaT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JComboBox<Cliente> jcbCliente;
    private javax.swing.JComboBox<Mascota> jcbMascota;
    // End of variables declaration//GEN-END:variables
}
